spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: server

  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
          